minsal_contrato_depuracion_medicamentos:
    path:     /depuracion/{incremento}/{contrato}
    defaults: { _controller: MinsalContratoBundle:Medicamento:depuracion }

minsal_contrato_listado_medicamentos:
    path:     /listado/{incremento}
    defaults: { _controller: MinsalContratoBundle:Medicamento:listado }