minsal_contrato_depuracion_medicamentos:
    path:     /depuracion/{incremento}/{contrato}/{proveedor}
    defaults: { _controller: MinsalContratoBundle:Medicamento:depuracion }

minsal_contrato_listado_medicamentos:
    path:     /listado/{incremento}
    defaults: { _controller: MinsalContratoBundle:Medicamento:listado }

minsal_contrato_cambiar_estado:
    path:     /cambiarEstadoProceso
    defaults: { _controller: MinsalContratoBundle:Medicamento:cambioEstado }

minsal_contrato_cambiar_estado_medicamento:
    path:     /estadoMedicamentoAjax
    defaults: { _controller: MinsalContratoBundle:Medicamento:estadoMedicamentos }

minsal_contrato_listado_medicamentos_prorroga:
  path:     /listadoProrroga/{prorroga}
  defaults: { _controller: MinsalContratoBundle:Medicamento:listadoParaProrroga }

minsal_incremento_cambiar_estado:
  path:     /estadoIncrementoAjax
  defaults: { _controller: MinsalContratoBundle:Analizador:estadoIncrementoA }

minsal_contrato_depuracion_medicamentos_prorroga:
  path:     /depuracion/{prorroga}/{contrato}/{proveedor}
  defaults: { _controller: MinsalContratoBundle:Medicamento:depuracionProrroga }
