# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
       our_db_provider:
            entity:
                class: MinsalModeloBundle:CtlUsuario
                property: usuario

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /
                check_path: /login_check
                username_parameter: _usuario
                password_parameter: _clave

            logout:
                path: /logout
                target: /

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
