# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html

security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
       our_db_provider:
            entity:
                class: MinsalUsuarioBundle:SegUsuario
                property: nombre

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                success_handler: login_success_handler
                username_parameter: _nombre
                password_parameter: _password

            logout:
                path: /logout
                target: /login

        main:
            anonymous: ~

    encoders:
        Minsal\UsuarioBundle\Entity\SegUsuario:
            algorithm: bcrypt
            cost: 12

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/inicioProceso, roles: ROLE_UNABAST }
        - { path: ^/medicamentos/listado, roles: ROLE_UNABAST }
        - { path: ^/uaci/listadoProcesos, roles: ROLE_UACI }
        - { path: ^/uaci/proveedoresUaci/, roles: ROLE_UACI }

services:
    login_success_handler:
        class: AppBundle\LoginSuccessHandler
        arguments: ['@router', '@security.context',]
        tags:
        - { name: 'monolog.logger', channel: 'security' }
    # ...

    
