# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
       our_db_provider:
            entity:
                class: MinsalUsuarioBundle:SegUsuario
                property: nombre

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                username_parameter: _nombre
                password_parameter: _password

            logout:
                path: /logout
                target: /login

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    encoders:
        Minsal\UsuarioBundle\Entity\SegUsuario:
            algorithm: bcrypt
            cost: 12

    # role_hierarchy:
    #     ROLE_ADMIN: Admin
