minsal_contrato_inicio_depurar_medicamentos:
    path:     /depurarMedicamentos
    defaults: { _controller: MinsalContratoBundle:InicioProceso:depurarMedicamentos }

minsal_contrato_inicio_proceso_inicio:
    path:     /
    defaults: { _controller: MinsalContratoBundle:InicioProceso:inicio }

minsal_contrato_inicio_proceso_crear:
  path:       /crear
  defaults:   { _controller:MinsalContratoBundle:InicioProceso:crearIncremento }
  methods:    POST