minsal_contrato_listado_proceso:
    path:     /listadoProcesos
    defaults: { _controller: MinsalContratoBundle:Uaci:uaciInicio }

minsal_contrato_proveedores_uaci:
    path:     /proveedoresUaci/{cod}/{tipo}/{licitacion}
    defaults: { _controller: MinsalContratoBundle:Uaci:proveedorUaci }
    methods: GET
    requirements:
          "licitacion": ".+"

minsal_contrato_estado_proveedores:
    path:       /cambiarEstado
    defaults:   { _controller:MinsalContratoBundle:Uaci:cambiarEstado }
    methods:    POST

minsal_detalle_observacion:
    path: /detallesObservacion/{incremento}
    defaults:   { _controller:MinsalContratoBundle:Uaci:detallesObservacion }

minsal_contrato_agregar_observacion:
    path:       /observacionAjax
    defaults:   { _controller:MinsalContratoBundle:Uaci:agregarObservacion }
    methods:    POST

minsal_contrato_estado_negociacion:
    path:       /negociacionAjax
    defaults:   { _controller:MinsalContratoBundle:Uaci:estadoNegociacion }
    methods:    POST


    