minsal_contrato_listado_proceso:
    path:     /listadoProcesos
    defaults: { _controller: MinsalContratoBundle:Uaci:uaciInicio }

minsal_contrato_proveedores_uaci:
    path:     /proveedoresUaci/{cod}
    defaults: { _controller: MinsalContratoBundle:Uaci:proveedorUaci }
    methods: GET
    requirements:
        "cod": ".+"

minsal_contrato_estado_proveedores:
    path:       /cambiarEstado
    defaults:   { _controller:MinsalContratoBundle:Uaci:cambiarEstado }
    methods:    POST