minsal_contrato_listado_proceso:
    path:     /listadoProcesos
    defaults: { _controller: MinsalContratoBundle:Uaci:uaciInicio }

minsal_contrato_proveedores_uaci:
    path:     /proveedoresUaci/{cod}
    defaults: { _controller: MinsalContratoBundle:Uaci:proveedorUaci }