minsal_contrato_analizador_dashboard:
    path:     /dashboard/{incremento}/{contrato}
    defaults: { _controller: MinsalContratoBundle:Analizador:dashboard }

minsal_contrato_analizador_contratos:
    path:     /listado/{incremento}
    defaults: { _controller: MinsalContratoBundle:AnalizadorIncremento:listado}

minsal_contrato_analizador_ajax_guardar:
    path:     /guardar
    defaults: { _controller: MinsalContratoBundle:Analizador:guardarIncremento}
    methods:  POST

minsal_contrato_analizador_prorroga:
  path: /listadoProrroga
  defaults: { _controller: MinsalContratoBundle:Analizador:analizadorProrroga }
