minsal_contrato_analizador_dashboard:
    path:     /dashboard/{incremento}/{contrato}
    defaults: { _controller: MinsalContratoBundle:Analizador:dashboard }

minsal_contrato_analizador_contratos:
    path:     /listado/{incremento}
    defaults: { _controller: MinsalContratoBundle:Analizador:listado}
