minsal_usuario_homepage:
    path:     /inicioLogin
    defaults: { _controller: MinsalUsuarioBundle:Default:index }

minsal_usuario_login:
    path:     /login
    defaults: { _controller: MinsalUsuarioBundle:Security:login }


minsal_usuario_login_check:
    path:     /login_check
    defaults: { _controller: MinsalUsuarioBundle:Security:loginCheck }


minsal_usuario_logout:
    path:     /logout
   