minsal_contrato_listado_medicamentos:
    path:     /medicamentos
    defaults: { _controller: MinsalContratoBundle:Unabas:medicamentos }

minsal_contrato_listado_contratos:
    path:     /contratos
    defaults: { _controller: MinsalContratoBundle:Unabas:contratos }

minsal_contrato_mensajeria:
    path:     /correoAjax
    defaults: { _controller: MinsalContratoBundle:Unabas:mensajeria }


minsal_contrato_resultado_negociacion:
    path:     /detalleNegociacion
    defaults: { _controller: MinsalContratoBundle:Unabas:detalleNegociacion }